### PR TITLE
Stack Dropper v1.1

### PR DESCRIPTION
**Pull request by WiredSpast**
New features:

-  Added BC catalog support
-  Placing stops automatically when room, height or BC limit is reached
-  Upgraded to use G-Earth 1.5.2 jar

### CODE REVIEW

**Comment by sirjonasxx** [comment]
Goeie

**Comment by WiredSpast** [comment]
> Goeie

The ratelimit for placing bc items is surprisingly low, it places 500 items in 1 min and 36 seconds so about 5.2 items a second

**Comment by WiredSpast** [comment]
If the stacktile didn't have to be updated every item it could theoretically reach 5.7 items a second

**Comment by sirjonasxx** [comment]
Yeah, ratelimit for BC is luckily an adjusted one

**Pull request merged**
