### PR TITLE
Added simple UI, changed !average to !avg

### PR DESCRIPTION
**Pull request by rocawear-public**
Added simple UI, changed command and screenshot

### CODE REVIEW

**Comment by rocawear-public** [comment]
This should be correctly done now, from 1.2 to 1.2.1 versioning.

- Added simple UI that can be opened from "Extensions" tab
- Changed !average to !avg
- Changed from module to commonjs
- Added electron with simple UI
- Downgraded node-fetch and changed fetch function abit and getItemName function

**Review by WiredSpast — CHANGES_REQUESTED** [review]
Add this in, otherwise electron will keep running in the background when the extension gets terminated from G-Earth itself 
```js
ext.on('socketdisconnect', () => {
  process.exit(0);
});
```

**Comment by WiredSpast** [comment]
You are combining the flooritems and wallitems into 1 array but these have concurrent typeIds, which means it can possible give the name of the floor item when it needs the wallitem or vice versa

https://github.com/rocawear-public/habbo-average/blob/main/index.js#L96-L110

For example on .com you have
```json
{
  "id":3001,
  "classname":"xmas08_chair",
  "revision":48478,
  "category":"chair",
  "defaultdir":0,
  "xdim":1,
  "ydim":1,
  "name":"Icy Chair",
  "description":"Make sure you're wearing your long johns or you'll freeze your little pixels off...",
  "adurl":null,
  "offerid":-1,
  "buyout":false,
  "rentofferid":-1,
  "rentbuyout":false,
  "bc":false,
  "excludeddynamic":true,
  "customparams":null,
  "specialtype":1,
  "canstandon":false,
  "cansiton":true,
  "canlayon":false,
  "furniline":"arctic",
  "environment":null,
  "rare":false
}
``` 
as a floor item and 
```json
{
  "id":3001,
  "classname":"wallpaper",
  "revision":45512,
  "category":"space",
  "name":null,
  "description":null,
  "adurl":null,
  "specialtype":2,
  "furniline":"spaces",
  "environment":"",
  "rare":false,
  "offerid":9714,
  "buyout":true,
  "rentofferid":-1,
  "rentbuyout":false,
  "bc":false,
  "excludeddynamic":false
}
```
as a wall item

**Comment by WiredSpast** [comment]
The first int here also says whether it's a wall or floor item 
https://github.com/rocawear-public/habbo-average/blob/a4acb639b9d40d813c83aa11847f2c7a9123ee21/index.js#L122

image

**Review by WiredSpast — APPROVED** [review]

**Pull request merged**
