### PR TITLE
Update G-itemViewer

### PR DESCRIPTION
**Pull request by bolognesandwiches**
UI improvements (bigger font, lighter colour), trade sounds and macOS build

### CODE REVIEW

**Comment by WiredSpast** [comment]
Those sound bites are barely audible xD

**Comment by bolognesandwiches** [comment]
they sound ok to me, i generated them from here https://www.tetyys.com/SAPI4/

**Comment by WiredSpast** [comment]
Add an opt-in for the soundbites (so disabled by default but can be turned on with a checkbox), I don't want people to get confused by where weird noises come from

**Comment by bolognesandwiches** [comment]
@WiredSpast Added as opt-out toggle - think it's better that way but can change if needed

**Comment by WiredSpast** [comment]
Preferably disabled at the start, otherwise it will certainly confuse users

**Comment by WiredSpast** [comment]
I also just noticed something else that actually should have been handled in the first PR, but that's my fault that I didn't notice it sooner.
Any extension with a UI should not open the UI by default, but have the UI open using the playbutton

**Comment by bolognesandwiches** [comment]
okay, let's hold this PR for now, I will fix the UI opening by default later this evening.

**Comment by bolognesandwiches** [comment]
@WiredSpast Updated to now only start the application / show window when the playbutton is pressed. Closing the application will disconnect and kill the process.

**Comment by WiredSpast** [comment]
Yeah that's not how it's supposed to work in store extensions.
Click playbutton -> Toggle UI (Show if hidden, hide if shown)
Click close button in extension -> Hide UI
G-Earth socket disconnects -> Close extension

**Comment by bolognesandwiches** [comment]
@WiredSpast Thanks, and sorry for the confusion. There aren't any Go scripts with UI apart from G-Wallmover, and even that has weird behaviour

Now when the extension is installed (or G-Earth is launched with it already installed)

1) Extension is Initialized/Active but the UI does not appear until the playbutton is pressed
2) The playbutton will toggle UI visibility (Show if hidden, hide if shown)
3) Clicking X in the extension will only hide the UI
4) Disconnecting will quit the application and terminate the process
5) Restarting the extension goes back to step 1

Please let me know if I missed anything.

**Pull request merged**
