### PR TITLE
Mod Tools 2.2

### PR DESCRIPTION
**Pull request by funkydemir66**
change icon

### CODE REVIEW

**Comment by Alynva** [comment]
Please, fix your `extension.json`

**Comment by funkydemir66** [comment]
okey fixed

**Comment by Alynva** [comment]
I think that you shouldn't change the `submissionDate`

**Comment by funkydemir66** [comment]
what's the problem there

**Comment by Alynva** [comment]
> what's the problem there

I think that's when you first published the extension to the store, but I thought that the test would flag that error

**Comment by sirjonasxx** [comment]
yeah submissiondate shouldn't change, we can see to add tests for that

**Comment by funkydemir66** [comment]
okey i made it

**Comment by Alynva** [comment]
We talked about only the `submissionDate`. The `updateDate` you have to change as it was before

**Comment by funkydemir66** [comment]
okey i made it

**Comment by funkydemir66** [comment]
hey?

**Review by Alynva — APPROVED** [review]

**Pull request merged**
