### PR TITLE
rainbow bg

### PR DESCRIPTION
**Pull request by Laande**
please tell me if there are any errors

### CODE REVIEW

**Comment by Laande** [comment]
oh maybe i just see the "commands" idk what to put here

**Comment by WiredSpast** [comment]
You're extension.json file is completely wrong you have to edit more than only the title

**Comment by Laande** [comment]
@WiredSpast lmao i miss my c/c

**Comment by WiredSpast** [comment]
You're language and run command are still incorrect

```json
    "language": "Java",
    "commands": {
      "default": ["java", "-jar", "GClick.jar", "-c", "{cookie}", "-p", "{port}", "-f", "{filename}"]
    },
```
Should be
```json
    "language": "Python",
    "commands": {
      "default": ["python", "Rainbow_BG.py", "-c", "{cookie}", "-p", "{port}", "-f", "{filename}"]
    },
```

**Pull request merged**
