### PR TITLE
Mod Tools for G Earth 

### PR DESCRIPTION
**Pull request by funkydemir66**
Source: Python

I don't know exactly how to pull request, sorry if I made a mistake.

### CODE REVIEW

**Comment by WiredSpast** [comment]
Euh I'm going to have to ask you to create a new fork and then try again because it's way to complicated to review this pull request with all those upstream fetches in the change logs

**Comment by WiredSpast** [comment]
Oh and also push into 1.5.2 instead of 1.4.1

**Comment by sirjonasxx** [comment]
yes 1.5.2 please!

**Comment by funkydemir66** [comment]
https://www.hizliresim.com/57p7jdx
but i added my extension folder to store
it doesn't detect it

**Comment by funkydemir66** [comment]
i open

**Pull request closed without merging**
