### PR TITLE
Removed my extensions

### PR DESCRIPTION
**Pull request by rocawear-public**

### CODE REVIEW

**Comment by sirjonasxx** [comment]
How come you're removing them?

**Comment by JonasssC** [comment]
> How come you're removing them?

I've never seen you react to a PR that fast

**Comment by WiredSpast** [comment]
> How come you're removing them?

I've never seen you reply to a PR that fast

**Comment by rocawear-public** [comment]
All good things come to an end, will delete this github user and don't want to have those extensions installable.

**Comment by rocawear-public** [comment]
No reason, just want to get them removed. Thanks.

**Comment by sirjonasxx** [comment]
too bad about the shopper extension, seemed to be popular

**Pull request merged**
